version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: next_wm
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: password # IDK why but it's not used
      MYSQL_ROOT_PASSWORD: password # IDK why but it's not used
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: